### ISSUE TITLE
Dijkstra fails on sparse graph

### ISSUE THREAD

**Issue by pgcassidy2004** [aalhour/C-Sharp-Algorithms#13]
With many vertices and not many edges, the Dijkstra algorithm fails on the following line:
//_edgeTo = new WeightedEdge<TVertex>[_edgesCount];
which now runs with the following line:
 _edgeTo = new WeightedEdge<TVertex>[_verticesCount];

Similarly the test for optimality fails in DijkstraShortestPaths with directed edges, I think because code fails due to adding an edge weight to Infinity, when it should not do this for the directed edge when the edge is not in the right direction.

//Debug.Assert(_checkOptimalityConditions(Graph, Source));

(_distances[v] + edge.Value < _distances[w])
 infinity + an edge weight will be less than distances[w](infinity + positive number) = small number.

**Comment by aalhour** [comment]
Hi there.

Thanks for reporting this. I will try to fix it as soon as my time allows. If you know how to solve this, and wish to contribute to this repository, then fix it and I'll be happy to review and merge your pull request.

Cheers!

**Comment by pgcassidy2004** [comment]
Ahmad,
here is the patch for the modifications I made.
Not sure about pull requests.


On Mon, Sep 14, 2015 at 11:13 AM, Ahmad Alhour <notifications@github.com>
wrote:

> Hi there.
>
> Thanks for reporting this. I will try to fix it as soon as my time allows.
> If you know how to solve this, and wish to contribute to this repository,
> then fix it and I'll be happy to review and merge your pull request.
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aalhour/C-Sharp-Algorithms/issues/13#issuecomment-140164036>
> .
>



-- 
Paul G Cassidy
CTO
