### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by ZwoRmi** [aalhour/C-Sharp-Algorithms#17]
Hello,

There are many `static class` which are testing algorithms and data structures implementations. Why not creating a unit testing project instead (or additionnaly)?

ZwoRmi

**Comment by aalhour** [comment]
Hi,

Thanks for passing by. The MainProgram is actually the testing project. I was thinking of refactoring all the tests to use NUnit or a similar unit testing library, and rewrite the classes accordingly.

**Comment by ZwoRmi** [comment]
I will do a pull request soon with unit test of the sorting algorithm implementations.

**Comment by aalhour** [comment]
Awesome! :+1:
