### ISSUE TITLE
Graph by clans

### ISSUE THREAD

**Issue by karv** [aalhour/C-Sharp-Algorithms#3]
I have implemented an similar `IGraph<T>`, which acts like a undirected unweighted graph. 
It should be fast at finding paths and other connexity algorimths; but slower at direct manipulation like adding or removing edges.

It stores in memory the clan: the maximal complete subgraphs in `ISet<T>`'s 

If you are interesed i could implement it to your `IGraph<T>` interface and merge it.

**Comment by aalhour** [comment]
Hi karv, that sounds like a fantastic idea. Can you help me understand more first? And what do you think the impact and scope of source code changes of your new implementation?

**Comment by karv** [comment]
After I re-read my comment I notice I was not clear enough.

I want to add a new class which implements your `IGraph<T>`; 
your code will be untouched.

**Comment by aalhour** [comment]
That's nice. Help me more with the GitHub pull requests workflow, submit the class and we will review the styling together, if it's like the other classes with short <summary></summary> tags I will merge right it away. :)

Looking forward for the first ever algorithmic contribution. :)

**Comment by aalhour** [comment]
One more thing, can you please add a test for it under the MainProgram project, DataStructuresTests directory?

**Comment by karv** [comment]
Yes, working on [this](https://en.wikipedia.org/wiki/Clique_(graph_theory)).
Constructor from `IGraph` seems to be working (since it is much look faster to add edges in some other `IGraph` and then convert it to `CliqueGraph`)

It can produce a dual graph, another `IGraph` which may be simpler and conserves all the information about conexity. In the test, it is produced a graph of 100 vertices to one of 11. One may calculate some path in the dual graph and translate it to the original. Preserves 'most short'ness.

I need to work in some other implementaion of `IGraph` into it

**Comment by aalhour** [comment]
Looking forwards to see your implementation.

**Comment by aalhour** [comment]
The pull request was merged. I had to cleanup the indentation space via Visual Studio. I also added an underscore in front of the private methods. Didn't change anything else. I also added you to the list of contributors. Check the README.md and the source code at my repo. Thanks for your contribution.
