### ISSUE TITLE
B Trees

### ISSUE THREAD

**Issue by aalhour** [aalhour/C-Sharp-Algorithms#31]
Implement the [B Tree](https://en.wikipedia.org/wiki/B-tree) Data Structure.

**Comment by j-rewerts** [comment]
I'll implement this.

**Comment by aalhour** [comment]
Alright, thanks @j-rewerts for taking initiative on this.

**Comment by aalhour** [comment]
Please assign the ticket to yourself @j-rewerts.

**Comment by j-rewerts** [comment]
@aalhour I don't think I can?
