### ISSUE TITLE
[Strings/Permutations] - Anagram detecting

### ISSUE THREAD

**Issue by ivandrofly** [aalhour/C-Sharp-Algorithms#35]
I have written a optimized version of Anagram detecting, do you guys accept optimization?

**Before: 2n+2(n log n)+n**
**After: 3n**

**Comment by aalhour** [comment]
Hello @ivandrofly, sorry for the late reply, yes we definitely accept optimizations. Waiting for your pull request!

**Comment by aalhour** [comment]
Hello @ivandrofly, any news on your optimizations PR?

**Comment by ivandrofly** [comment]
> Hello @ivandrofly, any news on your optimizations PR?

Oh yeah... will be send soon!

**Comment by ivandrofly** [comment]
https://github.com/aalhour/C-Sharp-Algorithms/pull/37

**Comment by aalhour** [comment]
Hello @ivandrofly,

Sorry for the late reply, going through the PR now.

**Comment by aalhour** [comment]
Hey @ivandrofly, I am going to close this issue since we reached an agreement on the next steps.
