### ISSUE TITLE
SortedDictionaryTests and DLinkedListTest fail to pass

### ISSUE THREAD

**Issue by hbsock** [aalhour/C-Sharp-Algorithms#39]
On the current master 9fc09bd2ce8db1542, it seems that these two tests don't pass.

Example code that fails in DLinkedListTest:
```cs
            /****************************************************************************************/
            var stringsIterators = listOfStrings.GetEnumerator();

            Debug.Assert(stringsIterators.Current == listOfStrings[0], "Wrong enumeration.");
```

Example code that fails in SortedDictionaryTests:
```cs
            Debug.Assert(sortedDict["Bic"] == 12);
            Debug.Assert(sortedDict["Carter"] == 13);
```

The errors were very minor (typos, forgetting to undo updates, etc), so I've fixed them myself.

 Would it be okay for me to send a pull request for this?

**Comment by aalhour** [comment]
Hello @hbsock,

Thanks for spotting this, this is absolutely a good fix, please do submit a PR!

Cheers,
Ahmad
