### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by christianbender** [aalhour/C-Sharp-Algorithms#52]
@aalhour Can I help you by coding? This is my first open source-project.
@maxm2017

**Comment by aalhour** [comment]
Hello @christianbender,

Yes, sure. Take a look at the open issues, pick one and let's discuss it there.

Cheers,
Ahmad

**Comment by christianbender** [comment]
@aalhour  thank you. I have seen in the TODO-list that must build a Bit-Array. At the moment I do so.
