### ISSUE TITLE
Make Travis CI run tests from the UnitTest project

### ISSUE THREAD

**Issue by aalhour** [aalhour/C-Sharp-Algorithms#68]
Currently, Travis CI doesn't run tests from the UnitTest project when building the project, I want it to run all tests as part of the build process.

**Comment by aalhour** [comment]
Hi @ivandrofly, do you have any idea how to do this?

**Comment by ivandrofly** [comment]
> Hi @ivandrofly, do you have any idea how to do this?

Haven't done it in past, but I can take a look at their [documentation](https://docs.travis-ci.com/user/languages/csharp/), doesn't seems that hard 😉

**Comment by ivandrofly** [comment]
Okay, I'll go with small patches. There is not much thing to do actually, there is only couple united-test that needs some refact due to the change to dotnet core. < 15 tests

**Comment by aalhour** [comment]
Closing this one as it's already implemented by @PatrykOlejniczak in #79.
