### ISSUE TITLE
Multiple issues with catalan numbers

### ISSUE THREAD

**Issue by nickntg** [aalhour/C-Sharp-Algorithms#74]
Specifically:

- The algorithm does not produce correct numbers when large ranks are used.
- The implementation of GetNumberByBinomialCoefficients() produces different results when rank >= 32.
- As a result of the above, CatalanNumbersTest.DoTest() fails.
- There are no tests to validate the algorithm implementation against known and documented catalan numbers.

**Comment by aalhour** [comment]
Closing this as #75 is now merged.
