### ISSUE TITLE
Greatest Common Divisor algoritm not working

### ISSUE THREAD

**Issue by 007souvikdas** [aalhour/C-Sharp-Algorithms#87]
FindGCD() is not working as expected.It runs as infinite loop if I try to find a GCD of 4,5 with value of r =4 everytime.

**Comment by 007souvikdas** [comment]
Solution:
Please replace findGCD() with the following method:

public static uint FindGCD(uint a, uint b)
        {

			if (a == 0)
				return b;
			if (b == 0)
				return a;
			//following stien's algorithm

			if ((~a & 1) == 1) {//a is even
				if ((~b & 1) == 1) { //b is also even
					return FindGCD (a >> 1, b >> 1) << 1;
				} else {
					return FindGCD (a >> 1, b);
				}
			} else {// a is odd
				if ((~b & 1) == 1) {//b is even
					return FindGCD(a,b<<1);
				}
			}
			//both a, b are odd
			return a>b?FindGCD((a-b)>>1,b):FindGCD(a,(b-a)>>1);
        }

**Comment by 007souvikdas** [comment]
Solution:
Please remove the FindGCD() with the following:


public static uint FindGCD(uint a, uint b)
        {

			if (a == 0)
				return b;
			if (b == 0)
				return a;
			//following stien's algorithm

			if ((~a & 1) == 1) {//a is even
				if ((~b & 1) == 1) { //b is also even
					return FindGCD (a >> 1, b >> 1) << 1;
				} else {
					return FindGCD (a >> 1, b);
				}
			} else {// a is odd
				if ((~b & 1) == 1) {//b is even
					return FindGCD(a,b<<1);
				}
			}
			//both a, b are odd
			return a>b?FindGCD((a-b)>>1,b):FindGCD(a,(b-a)>>1);
        }

**Comment by 007souvikdas** [comment]
Solution:
Please remove the FindGCD() with the following:


public static uint FindGCD(uint a, uint b)
        {

			if (a == 0)
				return b;
			if (b == 0)
				return a;
			//following stien's algorithm

			if ((~a & 1) == 1) {//a is even
				if ((~b & 1) == 1) { //b is also even
					return FindGCD (a >> 1, b >> 1) << 1;
				} else {
					return FindGCD (a >> 1, b);
				}
			} else {// a is odd
				if ((~b & 1) == 1) {//b is even
					return FindGCD(a,b<<1);
				}
			}
			//both a, b are odd
			return a>b?FindGCD((a-b)>>1,b):FindGCD(a,(b-a)>>1);
        }

**Comment by marianorapa** [comment]
Hi! There's the cleaner and simpler recursive solution based on Euclides' algorithm, not sure if more efficient though, due to the amount of divisions. Nevertheless, it's still O (log n). Should I pull the request or it's already fixed? Also, why shouldn't it allow negative numbers?

**Comment by ivandrofly** [comment]
> Should I pull the request

Sounds good! :)

**Comment by aalhour** [comment]
Hi @marianorapa and @007souvikdas,

Can you please check PR #104? Does it fix your notes?

**Comment by RyanGrange** [comment]
As an improvement to this fix, I have created https://github.com/aalhour/C-Sharp-Algorithms/pull/131 to alter the recursive function call into a while loop that accomplishes the same task without consuming stack space.

**Comment by RyanGrange** [comment]
I had to close https://github.com/aalhour/C-Sharp-Algorithms/pull/131 because I combined another commit with it by mistake.  I'll redo them both so they show up as separate PRs.

**Comment by RyanGrange** [comment]
https://github.com/aalhour/C-Sharp-Algorithms/pull/132 created to alleviate the stack space needed for recursive function calls with a while loop.
